name: build-carteira-daily
on:
  schedule:
    - cron: "0 9 * * *"   # 09:00 UTC ≈ 06:00 BRT (ajuste se quiser outro horário)
  workflow_dispatch:       # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # necessário para dar git push com o CSV
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt
      - run: pip install -r requirements.txt

      - name: Gerar carteira
        env:
          API_FINTZ: ${{ secrets.API_FINTZ }}   # injeta seu secret como variável de ambiente
        run: python scripts/make_carteira.py    # este script deve salvar data/Carteira_atual.csv

      - name: Commit CSV atualizado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/Carteira_atual.csv
          git commit -m "Atualiza carteira diária [skip ci]" || echo "Sem mudanças"
          git push
