# .github/workflows/build_carteira.yml
name: build-carteira-daily

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC (≈ 03:00 BRT). Ajuste se quiser outro horário.
  workflow_dispatch:       # permite rodar manualmente

concurrency:
  group: build-carteira-daily
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write      # necessário para fazer git push com o GITHUB_TOKEN

    env:
      API_FINTZ: ${{ secrets.API_FINTZ }}  # cadastre em Settings > Secrets > Actions

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip                      # cache automático de deps do pip

      - name: Install deps
        run: pip install -r requirements.txt

      # 1) Baixa/atualiza dados de mercado
      - name: Load data (Fintz)
        run: python scripts/load_data_fintz.py

      # 2) Calcula fatores/indicadores
      - name: Build factors
        run: python scripts/fazendo_indicador.py

      # 3) Monta carteira/resultado final
      - name: Run factor calculator
        run: python calculadora_factor.py

      # Commit ONLY dos arquivos/diretórios solicitados
      - name: Commit updated outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add \
            data/market_data/cdi.parquet \
            data/market_data/ibov.parquet \
            data/market_data/cotacoes.parquet \
            data/factors_data/
          git commit -m "Atualiza dados e fatores diários [skip ci]" || echo "Sem mudanças"
          git push
